admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: "@RestApiBundle/Controller/"
    type:     annotation
    prefix:   /api/v1.0

login:
    pattern: /login
    defaults: {_controller: AppBundle:Security:login}
    options: { i18n: false }

home:
    pattern: /
    defaults: {_controller: RestApiBundle:Default:index}

login_check:
    pattern:   /login_check
    options: { i18n: false }

logout:
    pattern:  /logout
    options: { i18n: false }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    options: { i18n: false }